### ISSUE TITLE
Syntax error in BringApi.py

### ISSUE THREAD

**Issue by Basti1512** [philipp2310/bring-api#3]
Since I updated the Bring! skill for Snips recently to the latest version I got the following syntax error in line 66 of BringApi.py:

`Jan 27 11:02:17 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner: [Philipp.bring_shopping][err] Traceback (most recent call last):
Jan 27 11:02:17 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner: [Philipp.bring_shopping][err]   File "./action-Philipp.bring_shopping.py", line 6, in <module>
Jan 27 11:02:17 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner: [Philipp.bring_shopping][err]     from BringApi.BringApi import BringApi
Jan 27 11:02:17 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner: [Philipp.bring_shopping][err]   File "/var/lib/snips/skills/snips-bring-shopping/venv/lib/python3.5/site-packages/BringApi/BringApi.py", line 66
Jan 27 11:02:17 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner: [Philipp.bring_shopping][err]     items = requests.get(f'{self._bringRestURL}bringlists/{self.bringListUUID}', headers=self.headers).json()
Jan 27 11:02:17 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner: [Philipp.bring_shopping][err]                                                                               ^
Jan 27 11:02:17 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner: [Philipp.bring_shopping][err] SyntaxError: invalid syntax
Jan 27 11:02:18 raspberrypi snips-skill-server[4011]: WARN:snips_skill_server_lib::handler::nosandbox: child Philipp.bring_shopping has stopped with status `exit code: 1`
Jan 27 11:02:18 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : restarting action Philipp.bring_shopping (restart_fails: 0)
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err] Traceback (most recent call last):
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]   File "./action-Philipp.bring_shopping.py", line 6, in <module>
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]     from BringApi.BringApi import BringApi
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]   File "/var/lib/snips/skills/snips-bring-shopping/venv/lib/python3.5/site-packages/BringApi/BringApi.py", line 66
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]     items = requests.get(f'{self._bringRestURL}bringlists/{self.bringListUUID}', headers=self.headers).json()
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]                                                                               ^
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err] SyntaxError: invalid syntax
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: WARN:snips_skill_server_lib::handler::nosandbox: child Philipp.bring_shopping has stopped with status `exit code: 1`
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : restarting action Philipp.bring_shopping (restart_fails: 1)
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err] Traceback (most recent call last):
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]   File "./action-Philipp.bring_shopping.py", line 6, in <module>
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]     from BringApi.BringApi import BringApi
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]   File "/var/lib/snips/skills/snips-bring-shopping/venv/lib/python3.5/site-packages/BringApi/BringApi.py", line 66
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]     items = requests.get(f'{self._bringRestURL}bringlists/{self.bringListUUID}', headers=self.headers).json()
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]                                                                               ^
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err] SyntaxError: invalid syntax
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: WARN:snips_skill_server_lib::handler::nosandbox: child Philipp.bring_shopping has stopped with status `exit code: 1`
Jan 27 11:02:19 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : restarting action Philipp.bring_shopping (restart_fails: 2)
Jan 27 11:02:20 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err] Traceback (most recent call last):
Jan 27 11:02:20 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]   File "./action-Philipp.bring_shopping.py", line 6, in <module>
Jan 27 11:02:20 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]     from BringApi.BringApi import BringApi
Jan 27 11:02:20 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]   File "/var/lib/snips/skills/snips-bring-shopping/venv/lib/python3.5/site-packages/BringApi/BringApi.py", line 66
Jan 27 11:02:20 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]     items = requests.get(f'{self._bringRestURL}bringlists/{self.bringListUUID}', headers=self.headers).json()
Jan 27 11:02:20 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err]                                                                               ^
Jan 27 11:02:20 raspberrypi snips-skill-server[4011]: INFO:snips_skill_server_lib::runner            : [Philipp.bring_shopping][err] SyntaxError: invalid syntax
Jan 27 11:02:20 raspberrypi snips-skill-server[4011]: WARN:snips_skill_server_lib::handler::nosandbox: child Philipp.bring_shopping has stopped with status `exit code: 1`
Jan 27 11:02:20 raspberrypi snips-skill-server[4011]: ERROR:snips_skill_server_lib::runner            : action Philipp.bring_shopping failed 3 times in the last 10 seconds, disabling it
`

I'm not that familiar with phyton but I think you are :-)

Best regards
Basti

**Comment by philipp2310** [comment]
Hi,
it is due to the python version 3.5
When I updated the skill to use with ProjectAlice, I updated it to a syntax only available in 3.7 (not precompiled for raspian stretch afaik).

The fastest way would be to use BringApi 0.0.3, that should be compatible. Will update the requirements file as soon as I’m on my pc

Or you could check out ProjectAlice by Psycho: https://github.com/project-alice-assistant/ProjectAlice

This will keep working after the 31.01. unlike snips!

Regards,
Philipp

**Comment by Basti1512** [comment]
Thx, that works for me.

BR, Basti

**Comment by philipp2310** [comment]
requirements.txt is updated - still only from mobile phone and without having a setup for testing myself. Can you please confirm if it works with the change for you?
Best regards,
Philipp

**Comment by Basti1512** [comment]
Hi Philipp,

I'm on a business trip and will return on Wednesday evening. I will check 
the new requirements.txt on Thursday.

Best regards,
Thomas

Am 28. Januar 2020 10:26:34 schrieb philipp2310 <notifications@github.com>:

**Comment by Basti1512** [comment]
Hi Philipp,

I was able to test the new version with the updated requirements.txt. It's 
working now. Thx a lot!

Regards,
Thomas

Am 28. Januar 2020 19:40:03 schrieb Thomas Hauswirth <t_hauswirth@t-online.de>:

**Comment by philipp2310** [comment]
Thank You for retesting! :)
Best wishes,
Philipp
